### ISSUE TITLE
GalaxyManager OnDestroy issue

### ISSUE THREAD

**Issue by GeorgiyRyaposov** [gogcom/galaxy-csharp-demo-game#1]
Hi!

I'm using code from GalaxyManager and StatsAndAchievements, and faced with issue

Repro steps:
Add to Scene1 GalaxyManager
Start game 
Reload Scene1
Try to unlock achievement
-> NRE

New instance of GalaxyManager at Awake call Destroy gameobject, because there is already instance of GalaxyManager, but on Destroy called:
GalaxyInstance.Shutdown(true);
what is not good, because first instance of GalaxyManager tries to use GalaxyInstance.Stats() which is null, and e.g. StatsAndAchievements throws NRE at achievement unlock, or during any other aciton with GalaxyInstance.Stats(), and it crashes the game.

To fix this you can replace OnDestroy to OnApplicationQuit at GalaxyManager 

Thanks!

P.S. at StatsAndAchievements all calls of GalaxyInstance.Stats() wrapped with try catch, but it catches only GalaxyInstance.Error, better to catch System.Exception

**Comment by JakBaranowski** [comment]
Hi @sxwx,

Thank you for the feedback. I will include this fix in the next push to the repo. :-)

**Comment by JakBaranowski** [comment]
Solution pushed to branch develop.

https://github.com/gogcom/galaxy-csharp-demo-game/blob/9596750ba5b16797e23cc17e6f6c3b642d7083a6/Assets/Scripts/GalaxyManager/GalaxyManager.cs#L111
